// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "SdpCallback.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSdpCallback final : ::djinni::JniInterface<::libdc::SdpCallback, NativeSdpCallback> {
public:
    using CppType = std::shared_ptr<::libdc::SdpCallback>;
    using CppOptType = std::shared_ptr<::libdc::SdpCallback>;
    using JniType = jobject;

    using Boxed = NativeSdpCallback;

    ~NativeSdpCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSdpCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeSdpCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeSdpCallback();
    friend ::djinni::JniClass<NativeSdpCallback>;
    friend ::djinni::JniInterface<::libdc::SdpCallback, NativeSdpCallback>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::libdc::SdpCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onSdp(const std::string & sdp) override;

    private:
        friend ::djinni::JniInterface<::libdc::SdpCallback, ::djinni_generated::NativeSdpCallback>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/cdnbye/libdc/SdpCallback") };
    const jmethodID method_onSdp { ::djinni::jniGetMethodID(clazz.get(), "onSdp", "(Ljava/lang/String;)V") };
};

}  // namespace djinni_generated
