// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include "LibDC.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeLibDC final : ::djinni::JniInterface<::libdc::LibDC, NativeLibDC> {
public:
    using CppType = std::shared_ptr<::libdc::LibDC>;
    using CppOptType = std::shared_ptr<::libdc::LibDC>;
    using JniType = jobject;

    using Boxed = NativeLibDC;

    ~NativeLibDC();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLibDC>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLibDC>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLibDC();
    friend ::djinni::JniClass<NativeLibDC>;
    friend ::djinni::JniInterface<::libdc::LibDC, NativeLibDC>;

};

} // namespace djinni_generated
