// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "NativeIceStateCallback.hpp"  // my header
#include "NativeIceState.hpp"

namespace djinni_generated {

NativeIceStateCallback::NativeIceStateCallback() : ::djinni::JniInterface<::libdc::IceStateCallback, NativeIceStateCallback>() {}

NativeIceStateCallback::~NativeIceStateCallback() = default;

NativeIceStateCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeIceStateCallback::JavaProxy::~JavaProxy() = default;

void NativeIceStateCallback::JavaProxy::onStateChanged(::libdc::IceState c_state) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeIceStateCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onStateChanged,
                           ::djinni::get(::djinni_generated::NativeIceState::fromCpp(jniEnv, c_state)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
