// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "ProxyServerType.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeProxyServerType final : ::djinni::JniEnum {
public:
    using CppType = ::libdc::ProxyServerType;
    using JniType = jobject;

    using Boxed = NativeProxyServerType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeProxyServerType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeProxyServerType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeProxyServerType() : JniEnum("com/cdnbye/libdc/ProxyServerType") {}
    friend ::djinni::JniClass<NativeProxyServerType>;
};

}  // namespace djinni_generated
