// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "TransportPolicy.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeTransportPolicy final : ::djinni::JniEnum {
public:
    using CppType = ::libdc::TransportPolicy;
    using JniType = jobject;

    using Boxed = NativeTransportPolicy;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeTransportPolicy>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeTransportPolicy>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeTransportPolicy() : JniEnum("com/cdnbye/libdc/TransportPolicy") {}
    friend ::djinni::JniClass<NativeTransportPolicy>;
};

}  // namespace djinni_generated
