// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#include "NativeLogCallback.hpp"  // my header
#include "Marshal.hpp"
#include "NativeLogLevel.hpp"

namespace djinni_generated {

NativeLogCallback::NativeLogCallback() : ::djinni::JniInterface<::libdc::LogCallback, NativeLogCallback>() {}

NativeLogCallback::~NativeLogCallback() = default;

NativeLogCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeLogCallback::JavaProxy::~JavaProxy() = default;

void NativeLogCallback::JavaProxy::onLog(::libdc::LogLevel c_level, const std::string & c_message) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeLogCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onLog,
                           ::djinni::get(::djinni_generated::NativeLogLevel::fromCpp(jniEnv, c_level)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_message)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} // namespace djinni_generated
