// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#include "NativeCandidateCallback.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeCandidateCallback::NativeCandidateCallback() : ::djinni::JniInterface<::libdc::CandidateCallback, NativeCandidateCallback>() {}

NativeCandidateCallback::~NativeCandidateCallback() = default;

NativeCandidateCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeCandidateCallback::JavaProxy::~JavaProxy() = default;

void NativeCandidateCallback::JavaProxy::onCandidate(const std::string & c_candidate, const std::string & c_mid) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeCandidateCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onCandidate,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_candidate)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_mid)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} // namespace djinni_generated
