// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "NativeProxyServer.hpp"  // my header
#include "Marshal.hpp"
#include "NativeProxyServerType.hpp"

namespace djinni_generated {

NativeProxyServer::NativeProxyServer() = default;

NativeProxyServer::~NativeProxyServer() = default;

auto NativeProxyServer::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeProxyServer>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni_generated::NativeProxyServerType::fromCpp(jniEnv, c.type)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.hostname)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.port)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(jniEnv, c.username)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(jniEnv, c.password)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeProxyServer::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeProxyServer>::get();
    return {::djinni_generated::NativeProxyServerType::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mType)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mHostname)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mPort)),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mUsername)),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPassword))};
}

}  // namespace djinni_generated
