// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include "LibVersion.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeLibVersion final : ::djinni::JniInterface<::libdc::LibVersion, NativeLibVersion> {
public:
    using CppType = std::shared_ptr<::libdc::LibVersion>;
    using CppOptType = std::shared_ptr<::libdc::LibVersion>;
    using JniType = jobject;

    using Boxed = NativeLibVersion;

    ~NativeLibVersion();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLibVersion>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLibVersion>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLibVersion();
    friend ::djinni::JniClass<NativeLibVersion>;
    friend ::djinni::JniInterface<::libdc::LibVersion, NativeLibVersion>;

};

} // namespace djinni_generated
