// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "SignalingStateCallback.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSignalingStateCallback final : ::djinni::JniInterface<::libdc::SignalingStateCallback, NativeSignalingStateCallback> {
public:
    using CppType = std::shared_ptr<::libdc::SignalingStateCallback>;
    using CppOptType = std::shared_ptr<::libdc::SignalingStateCallback>;
    using JniType = jobject;

    using Boxed = NativeSignalingStateCallback;

    ~NativeSignalingStateCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSignalingStateCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeSignalingStateCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeSignalingStateCallback();
    friend ::djinni::JniClass<NativeSignalingStateCallback>;
    friend ::djinni::JniInterface<::libdc::SignalingStateCallback, NativeSignalingStateCallback>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::libdc::SignalingStateCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onStateChanged(::libdc::SignalingState state) override;

    private:
        friend ::djinni::JniInterface<::libdc::SignalingStateCallback, ::djinni_generated::NativeSignalingStateCallback>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/cdnbye/libdc/SignalingStateCallback") };
    const jmethodID method_onStateChanged { ::djinni::jniGetMethodID(clazz.get(), "onStateChanged", "(Lcom/cdnbye/libdc/SignalingState;)V") };
};

}  // namespace djinni_generated
