// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "SignalingState.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSignalingState final : ::djinni::JniEnum {
public:
    using CppType = ::libdc::SignalingState;
    using JniType = jobject;

    using Boxed = NativeSignalingState;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeSignalingState>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeSignalingState>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeSignalingState() : JniEnum("com/cdnbye/libdc/SignalingState") {}
    friend ::djinni::JniClass<NativeSignalingState>;
};

}  // namespace djinni_generated
