// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "LogLevel.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeLogLevel final : ::djinni::JniEnum {
public:
    using CppType = ::libdc::LogLevel;
    using JniType = jobject;

    using Boxed = NativeLogLevel;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeLogLevel>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeLogLevel>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeLogLevel() : JniEnum("com/cdnbye/libdc/LogLevel") {}
    friend ::djinni::JniClass<NativeLogLevel>;
};

}  // namespace djinni_generated
