// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "ReliabilityType.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeReliabilityType final : ::djinni::JniEnum {
public:
    using CppType = ::libdc::ReliabilityType;
    using JniType = jobject;

    using Boxed = NativeReliabilityType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeReliabilityType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeReliabilityType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeReliabilityType() : JniEnum("com/cdnbye/libdc/ReliabilityType") {}
    friend ::djinni::JniClass<NativeReliabilityType>;
};

}  // namespace djinni_generated
