// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include "IceServerType.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeIceServerType final : ::djinni::JniEnum {
public:
    using CppType = ::libdc::IceServerType;
    using JniType = jobject;

    using Boxed = NativeIceServerType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeIceServerType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeIceServerType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeIceServerType() : JniEnum("com/cdnbye/libdc/IceServerType") {}
    friend ::djinni::JniClass<NativeIceServerType>;
};

} // namespace djinni_generated
