// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "NativeDcCallback.hpp"  // my header
#include "NativeDataChannel.hpp"

namespace djinni_generated {

NativeDcCallback::NativeDcCallback() : ::djinni::JniInterface<::libdc::DcCallback, NativeDcCallback>() {}

NativeDcCallback::~NativeDcCallback() = default;

NativeDcCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeDcCallback::JavaProxy::~JavaProxy() = default;

void NativeDcCallback::JavaProxy::onDataChannel(const std::shared_ptr<::libdc::DataChannel> & c_dc) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeDcCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onDataChannel,
                           ::djinni::get(::djinni_generated::NativeDataChannel::fromCpp(jniEnv, c_dc)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
