// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include "IceServerRelayType.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeIceServerRelayType final : ::djinni::JniEnum {
public:
    using CppType = ::libdc::IceServerRelayType;
    using JniType = jobject;

    using Boxed = NativeIceServerRelayType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeIceServerRelayType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeIceServerRelayType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeIceServerRelayType() : JniEnum("com/cdnbye/libdc/IceServerRelayType") {}
    friend ::djinni::JniClass<NativeIceServerRelayType>;
};

} // namespace djinni_generated
