// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include "DcEventCallback.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDcEventCallback final : ::djinni::JniInterface<::libdc::DcEventCallback, NativeDcEventCallback> {
public:
    using CppType = std::shared_ptr<::libdc::DcEventCallback>;
    using CppOptType = std::shared_ptr<::libdc::DcEventCallback>;
    using JniType = jobject;

    using Boxed = NativeDcEventCallback;

    ~NativeDcEventCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeDcEventCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeDcEventCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeDcEventCallback();
    friend ::djinni::JniClass<NativeDcEventCallback>;
    friend ::djinni::JniInterface<::libdc::DcEventCallback, NativeDcEventCallback>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::libdc::DcEventCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onEvent(::libdc::DcEvent event) override;

    private:
        friend ::djinni::JniInterface<::libdc::DcEventCallback, ::djinni_generated::NativeDcEventCallback>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/cdnbye/libdc/DcEventCallback") };
    const jmethodID method_onEvent { ::djinni::jniGetMethodID(clazz.get(), "onEvent", "(Lcom/cdnbye/libdc/DcEvent;)V") };
};

} // namespace djinni_generated
