// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "IceState.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeIceState final : ::djinni::JniEnum {
public:
    using CppType = ::libdc::IceState;
    using JniType = jobject;

    using Boxed = NativeIceState;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeIceState>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeIceState>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeIceState() : JniEnum("com/cdnbye/libdc/IceState") {}
    friend ::djinni::JniClass<NativeIceState>;
};

}  // namespace djinni_generated
