// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "DcErrorCallback.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDcErrorCallback final : ::djinni::JniInterface<::libdc::DcErrorCallback, NativeDcErrorCallback> {
public:
    using CppType = std::shared_ptr<::libdc::DcErrorCallback>;
    using CppOptType = std::shared_ptr<::libdc::DcErrorCallback>;
    using JniType = jobject;

    using Boxed = NativeDcErrorCallback;

    ~NativeDcErrorCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeDcErrorCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeDcErrorCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeDcErrorCallback();
    friend ::djinni::JniClass<NativeDcErrorCallback>;
    friend ::djinni::JniInterface<::libdc::DcErrorCallback, NativeDcErrorCallback>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::libdc::DcErrorCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onError(const std::string & error) override;

    private:
        friend ::djinni::JniInterface<::libdc::DcErrorCallback, ::djinni_generated::NativeDcErrorCallback>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/cdnbye/libdc/DcErrorCallback") };
    const jmethodID method_onError { ::djinni::jniGetMethodID(clazz.get(), "onError", "(Ljava/lang/String;)V") };
};

}  // namespace djinni_generated
