// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#include "NativeLibDC.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLibDC::NativeLibDC() : ::djinni::JniInterface<::libdc::LibDC, NativeLibDC>("com/cdnbye/libdc/LibDC$CppProxy") {}

NativeLibDC::~NativeLibDC() = default;


CJNIEXPORT void JNICALL Java_com_cdnbye_libdc_LibDC_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::libdc::LibDC>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_cdnbye_libdc_LibDC_version(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::libdc::LibDC::version();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
