// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include "PeerConnection.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativePeerConnection final : ::djinni::JniInterface<::libdc::PeerConnection, NativePeerConnection> {
public:
    using CppType = std::shared_ptr<::libdc::PeerConnection>;
    using CppOptType = std::shared_ptr<::libdc::PeerConnection>;
    using JniType = jobject;

    using Boxed = NativePeerConnection;

    ~NativePeerConnection();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePeerConnection>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePeerConnection>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePeerConnection();
    friend ::djinni::JniClass<NativePeerConnection>;
    friend ::djinni::JniInterface<::libdc::PeerConnection, NativePeerConnection>;

};

}  // namespace djinni_generated
