// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#include "NativeLibVersion.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLibVersion::NativeLibVersion() : ::djinni::JniInterface<::libdc::LibVersion, NativeLibVersion>("com/cdnbye/libdc/LibVersion$CppProxy") {}

NativeLibVersion::~NativeLibVersion() = default;


CJNIEXPORT void JNICALL Java_com_cdnbye_libdc_LibVersion_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::libdc::LibVersion>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_cdnbye_libdc_LibVersion_version(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::libdc::LibVersion::version();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
