// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#include "NativeDcErrorCallback.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeDcErrorCallback::NativeDcErrorCallback() : ::djinni::JniInterface<::libdc::DcErrorCallback, NativeDcErrorCallback>() {}

NativeDcErrorCallback::~NativeDcErrorCallback() = default;

NativeDcErrorCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeDcErrorCallback::JavaProxy::~JavaProxy() = default;

void NativeDcErrorCallback::JavaProxy::onError(const std::string & c_error) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeDcErrorCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onError,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_error)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} // namespace djinni_generated
