// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

/** log */
typedef NS_ENUM(NSInteger, DCLogLevel)
{
    DCLogLevelNone = 0,
    DCLogLevelFatal = 1,
    DCLogLevelError = 2,
    DCLogLevelWarning = 3,
    DCLogLevelInfo = 4,
    DCLogLevelDebug = 5,
    DCLogLevelVerbose = 6,
};
