// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DCProxyServerType)
{
    DCProxyServerTypeHttp = 0,
    DCProxyServerTypeSocks5 = 1,
};
