// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public interface CandidateCallback {
    void onCandidate(@NonNull String candidate, @NonNull String mid);
}
