// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import java.util.ArrayList;

public final class Configuration {


    /*package*/ final ArrayList<IceServer> mIceServers;

    /*package*/ final ProxyServer mProxyServer;

    /*package*/ final String mBindAddress;

    /*package*/ final CertificateType mCertificateType;

    /*package*/ final TransportPolicy mIceTransportPolicy;

    /*package*/ final boolean mEnableIceTcp;

    /*package*/ final boolean mEnableIceUdpMux;

    /*package*/ final boolean mDisableAutoNegotiation;

    /*package*/ final boolean mForceMediaTransport;

    /*package*/ final int mPortRangeBegin;

    /*package*/ final int mPortRangeEnd;

    /*package*/ final Integer mMtu;

    /*package*/ final Integer mMaxMessageSize;

    public Configuration(
            @NonNull ArrayList<IceServer> iceServers,
            @Nullable ProxyServer proxyServer,
            @Nullable String bindAddress,
            @NonNull CertificateType certificateType,
            @NonNull TransportPolicy iceTransportPolicy,
            boolean enableIceTcp,
            boolean enableIceUdpMux,
            boolean disableAutoNegotiation,
            boolean forceMediaTransport,
            int portRangeBegin,
            int portRangeEnd,
            @Nullable Integer mtu,
            @Nullable Integer maxMessageSize) {
        this.mIceServers = iceServers;
        this.mProxyServer = proxyServer;
        this.mBindAddress = bindAddress;
        this.mCertificateType = certificateType;
        this.mIceTransportPolicy = iceTransportPolicy;
        this.mEnableIceTcp = enableIceTcp;
        this.mEnableIceUdpMux = enableIceUdpMux;
        this.mDisableAutoNegotiation = disableAutoNegotiation;
        this.mForceMediaTransport = forceMediaTransport;
        this.mPortRangeBegin = portRangeBegin;
        this.mPortRangeEnd = portRangeEnd;
        this.mMtu = mtu;
        this.mMaxMessageSize = maxMessageSize;
    }

    @NonNull
    public ArrayList<IceServer> getIceServers() {
        return mIceServers;
    }

    @Nullable
    public ProxyServer getProxyServer() {
        return mProxyServer;
    }

    @Nullable
    public String getBindAddress() {
        return mBindAddress;
    }

    @NonNull
    public CertificateType getCertificateType() {
        return mCertificateType;
    }

    @NonNull
    public TransportPolicy getIceTransportPolicy() {
        return mIceTransportPolicy;
    }

    public boolean getEnableIceTcp() {
        return mEnableIceTcp;
    }

    public boolean getEnableIceUdpMux() {
        return mEnableIceUdpMux;
    }

    public boolean getDisableAutoNegotiation() {
        return mDisableAutoNegotiation;
    }

    public boolean getForceMediaTransport() {
        return mForceMediaTransport;
    }

    public int getPortRangeBegin() {
        return mPortRangeBegin;
    }

    public int getPortRangeEnd() {
        return mPortRangeEnd;
    }

    @Nullable
    public Integer getMtu() {
        return mMtu;
    }

    @Nullable
    public Integer getMaxMessageSize() {
        return mMaxMessageSize;
    }

    @Override
    public String toString() {
        return "Configuration{" +
                "mIceServers=" + mIceServers +
                "," + "mProxyServer=" + mProxyServer +
                "," + "mBindAddress=" + mBindAddress +
                "," + "mCertificateType=" + mCertificateType +
                "," + "mIceTransportPolicy=" + mIceTransportPolicy +
                "," + "mEnableIceTcp=" + mEnableIceTcp +
                "," + "mEnableIceUdpMux=" + mEnableIceUdpMux +
                "," + "mDisableAutoNegotiation=" + mDisableAutoNegotiation +
                "," + "mForceMediaTransport=" + mForceMediaTransport +
                "," + "mPortRangeBegin=" + mPortRangeBegin +
                "," + "mPortRangeEnd=" + mPortRangeEnd +
                "," + "mMtu=" + mMtu +
                "," + "mMaxMessageSize=" + mMaxMessageSize +
        "}";
    }

}
