// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class DataChannel {
    public abstract void close();

    public abstract boolean sendText(@NonNull String msg);

    public abstract boolean sendBinary(@NonNull byte[] msg);

    public abstract boolean isOpen();

    public abstract boolean isClosed();

    public abstract int maxMessageSize();

    public abstract int bufferedAmount();

    public abstract void onOpen(@Nullable DcEventCallback callback);

    public abstract void onClosed(@Nullable DcEventCallback callback);

    public abstract void onError(@Nullable DcErrorCallback callback);

    public abstract void onMessage(@Nullable DcMessageCallback callback);

    public abstract void onBufferedAmountLow(@Nullable DcEventCallback callback);

    public abstract void setBufferedAmountLowThreshold(int amount);

    public static final class CppProxy extends DataChannel
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public void close()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_close(this.nativeRef);
        }
        private native void native_close(long _nativeRef);

        @Override
        public boolean sendText(String msg)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_sendText(this.nativeRef, msg);
        }
        private native boolean native_sendText(long _nativeRef, String msg);

        @Override
        public boolean sendBinary(byte[] msg)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_sendBinary(this.nativeRef, msg);
        }
        private native boolean native_sendBinary(long _nativeRef, byte[] msg);

        @Override
        public boolean isOpen()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isOpen(this.nativeRef);
        }
        private native boolean native_isOpen(long _nativeRef);

        @Override
        public boolean isClosed()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isClosed(this.nativeRef);
        }
        private native boolean native_isClosed(long _nativeRef);

        @Override
        public int maxMessageSize()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_maxMessageSize(this.nativeRef);
        }
        private native int native_maxMessageSize(long _nativeRef);

        @Override
        public int bufferedAmount()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_bufferedAmount(this.nativeRef);
        }
        private native int native_bufferedAmount(long _nativeRef);

        @Override
        public void onOpen(DcEventCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onOpen(this.nativeRef, callback);
        }
        private native void native_onOpen(long _nativeRef, DcEventCallback callback);

        @Override
        public void onClosed(DcEventCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onClosed(this.nativeRef, callback);
        }
        private native void native_onClosed(long _nativeRef, DcEventCallback callback);

        @Override
        public void onError(DcErrorCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onError(this.nativeRef, callback);
        }
        private native void native_onError(long _nativeRef, DcErrorCallback callback);

        @Override
        public void onMessage(DcMessageCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onMessage(this.nativeRef, callback);
        }
        private native void native_onMessage(long _nativeRef, DcMessageCallback callback);

        @Override
        public void onBufferedAmountLow(DcEventCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onBufferedAmountLow(this.nativeRef, callback);
        }
        private native void native_onBufferedAmountLow(long _nativeRef, DcEventCallback callback);

        @Override
        public void setBufferedAmountLowThreshold(int amount)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setBufferedAmountLowThreshold(this.nativeRef, amount);
        }
        private native void native_setBufferedAmountLowThreshold(long _nativeRef, int amount);
    }
}
