// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public final class DataChannelInit {


    /*package*/ final Reliability mReliability;

    /*package*/ final boolean mNegotiated;

    /*package*/ final Short mId;

    /*package*/ final String mProtocol;

    public DataChannelInit(
            @NonNull Reliability reliability,
            boolean negotiated,
            @Nullable Short id,
            @NonNull String protocol) {
        this.mReliability = reliability;
        this.mNegotiated = negotiated;
        this.mId = id;
        this.mProtocol = protocol;
    }

    @NonNull
    public Reliability getReliability() {
        return mReliability;
    }

    public boolean getNegotiated() {
        return mNegotiated;
    }

    @Nullable
    public Short getId() {
        return mId;
    }

    @NonNull
    public String getProtocol() {
        return mProtocol;
    }

    @Override
    public String toString() {
        return "DataChannelInit{" +
                "mReliability=" + mReliability +
                "," + "mNegotiated=" + mNegotiated +
                "," + "mId=" + mId +
                "," + "mProtocol=" + mProtocol +
        "}";
    }

}
