// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public interface DcMessageCallback {
    public void onText(@NonNull String msg);

    public void onBinary(@NonNull byte[] msg);
}
