// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public interface LogCallback {
    public void onLog(@NonNull LogLevel level, @NonNull String message);
}
