// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/**
 *config end
 * DC start
 */
public enum ReliabilityType {
    RELIABLE,
    REXMIT,
    TIMED,
    ;
}
