// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public final class Reliability {


    /*package*/ final ReliabilityType mType;

    /*package*/ final boolean mUnordered;

    /*package*/ final long mRexmitMs;

    public Reliability(
            @NonNull ReliabilityType type,
            boolean unordered,
            long rexmitMs) {
        this.mType = type;
        this.mUnordered = unordered;
        this.mRexmitMs = rexmitMs;
    }

    @NonNull
    public ReliabilityType getType() {
        return mType;
    }

    public boolean getUnordered() {
        return mUnordered;
    }

    public long getRexmitMs() {
        return mRexmitMs;
    }

    @Override
    public String toString() {
        return "Reliability{" +
                "mType=" + mType +
                "," + "mUnordered=" + mUnordered +
                "," + "mRexmitMs=" + mRexmitMs +
        "}";
    }

}
