// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/**
 * DC end
 * PC start
 */
public interface SdpCallback {
    void onSdp(@NonNull String sdp);
}
