// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

package com.cdnbye.libdc;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public enum SignalingState {
    STABLE,
    HAVELOCALOFFER,
    HAVEREMOTEOFFER,
    HAVELOCALPRANSWER,
    HAVEREMOTEPRANSWER,
    ;
}
