[versions]
jvm = "17"
iosDeploymentTarget = "14.0"
agp = "8.7.3"
kotlin = "2.2.0"
compose = "1.8.3"

[libraries]
androidx-annotation = "androidx.annotation:annotation:1.9.1"
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-activity-compose = "androidx.activity:activity-compose:1.10.1"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
nexus-staging = "io.codearte.nexus-staging:0.30.0"
versions = "com.github.ben-manes.versions:0.52.0"
versionUpdate = "nl.littlerobots.version-catalog-update:1.0.0"
