// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>


@protocol DCCandidateCallback <NSObject>

- (void)onCandidate:(nonnull NSString *)candidate
                mid:(nonnull NSString *)mid;

@end
