// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DCGatheringState)
{
    DCGatheringStateNew = 0,
    DCGatheringStateInProgress = 1,
    DCGatheringStateComplete = 2,
};
