// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCSignalingState.h"
#import <Foundation/Foundation.h>


@protocol DCSignalingStateCallback <NSObject>

- (void)onStateChanged:(DCSignalingState)state;

@end
