// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DCSignalingState)
{
    DCSignalingStateStable = 0,
    DCSignalingStateHaveLocalOffer = 1,
    DCSignalingStateHaveRemoteOffer = 2,
    DCSignalingStateHaveLocalPranswer = 3,
    DCSignalingStateHaveRemotePranswer = 4,
};
