// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>


@protocol DCCandidateCallback

- (void)onCandidate:(nonnull NSString *)candidate
                mid:(nonnull NSString *)mid;

@end
