// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCCandidateCallback+Private.h"
#import "DCCandidateCallback.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class CandidateCallback::ObjcProxy final
: public ::libdc::CandidateCallback
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::CandidateCallback;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onCandidate(const std::string & c_candidate, const std::string & c_mid) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onCandidate:(::djinni::String::fromCpp(c_candidate))
                                                              mid:(::djinni::String::fromCpp(c_mid))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto CandidateCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto CandidateCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
