// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "CandidateCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DCCandidateCallback;

namespace djinni_generated {

class CandidateCallback
{
public:
    using CppType = std::shared_ptr<::libdc::CandidateCallback>;
    using CppOptType = std::shared_ptr<::libdc::CandidateCallback>;
    using ObjcType = id<DCCandidateCallback>;

    using Boxed = CandidateCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

