// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCConfiguration.h"
#include "Configuration.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DCConfiguration;

namespace djinni_generated {

struct Configuration
{
    using CppType = ::libdc::Configuration;
    using ObjcType = DCConfiguration*;

    using Boxed = Configuration;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
