// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCDataChannelInit+Private.h"
#import "DCReliability+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto DataChannelInit::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni_generated::Reliability::toCpp(obj.reliability),
            ::djinni::Bool::toCpp(obj.negotiated),
            ::djinni::Optional<std::optional, ::djinni::I16>::toCpp(obj.id),
            ::djinni::String::toCpp(obj.protocol)};
}

auto DataChannelInit::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DCDataChannelInit alloc] initWithReliability:(::djinni_generated::Reliability::fromCpp(cpp.reliability))
                                               negotiated:(::djinni::Bool::fromCpp(cpp.negotiated))
                                                       id:(::djinni::Optional<std::optional, ::djinni::I16>::fromCpp(cpp.id))
                                                 protocol:(::djinni::String::fromCpp(cpp.protocol))];
}

}  // namespace djinni_generated
