// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCDataChannelInit.h"
#include "DataChannelInit.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DCDataChannelInit;

namespace djinni_generated {

struct DataChannelInit
{
    using CppType = ::libdc::DataChannelInit;
    using ObjcType = DCDataChannelInit*;

    using Boxed = DataChannelInit;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
