// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>


@protocol DCDcErrorCallback

- (void)onError:(nonnull NSString *)error;

@end
