// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "DcMessageCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DCDcMessageCallback;

namespace djinni_generated {

class DcMessageCallback
{
public:
    using CppType = std::shared_ptr<::libdc::DcMessageCallback>;
    using CppOptType = std::shared_ptr<::libdc::DcMessageCallback>;
    using ObjcType = id<DCDcMessageCallback>;

    using Boxed = DcMessageCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

