// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>


@protocol DCDcErrorCallback <NSObject>

- (void)onError:(nonnull NSString *)error;

@end
