// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>
@class DCDataChannel;


@protocol DCDcCallback <NSObject>

- (void)onDataChannel:(nullable DCDataChannel *)dc;

@end
