// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "DcEventCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DCDcEventCallback;

namespace djinni_generated {

class DcEventCallback
{
public:
    using CppType = std::shared_ptr<::libdc::DcEventCallback>;
    using CppOptType = std::shared_ptr<::libdc::DcEventCallback>;
    using ObjcType = id<DCDcEventCallback>;

    using Boxed = DcEventCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

