// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>
@class DCDataChannel;


@protocol DCDcCallback

- (void)onDataChannel:(nullable DCDataChannel *)dc;

@end
