// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DCDcEvent)
{
    DCDcEventOpen = 0,
    DCDcEventClosed = 1,
    DCDcEventBufferedAmountLow = 2,
};
