// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "DcCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DCDcCallback;

namespace djinni_generated {

class DcCallback
{
public:
    using CppType = std::shared_ptr<::libdc::DcCallback>;
    using CppOptType = std::shared_ptr<::libdc::DcCallback>;
    using ObjcType = id<DCDcCallback>;

    using Boxed = DcCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

