// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCDcErrorCallback+Private.h"
#import "DCDcErrorCallback.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class DcErrorCallback::ObjcProxy final
: public ::libdc::DcErrorCallback
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::DcErrorCallback;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onError(const std::string & c_error) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onError:(::djinni::String::fromCpp(c_error))];
        }
    }
};

} // namespace djinni_generated

namespace djinni_generated {

auto DcErrorCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto DcErrorCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

} // namespace djinni_generated
