// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCGatheringState.h"
#import <Foundation/Foundation.h>


@protocol DCGatheringStateCallback <NSObject>

- (void)onStateChanged:(DCGatheringState)state;

@end
