// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCGatheringState.h"
#import <Foundation/Foundation.h>


@protocol DCGatheringStateCallback

- (void)onStateChanged:(DCGatheringState)state;

@end
