// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "GatheringStateCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DCGatheringStateCallback;

namespace djinni_generated {

class GatheringStateCallback
{
public:
    using CppType = std::shared_ptr<::libdc::GatheringStateCallback>;
    using CppOptType = std::shared_ptr<::libdc::GatheringStateCallback>;
    using ObjcType = id<DCGatheringStateCallback>;

    using Boxed = GatheringStateCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

