// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

/** config start */
typedef NS_ENUM(NSInteger, DCIceServerType)
{
    DCIceServerTypeStun,
    DCIceServerTypeTurn,
};
