// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DCIceState)
{
    DCIceStateNew = 0,
    DCIceStateConnecting = 1,
    DCIceStateConnected = 2,
    DCIceStateDisconnected = 3,
    DCIceStateFailed = 4,
    DCIceStateClosed = 5,
};
