// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DCIceState)
{
    DCIceStateNew,
    DCIceStateConnecting,
    DCIceStateConnected,
    DCIceStateDisconnected,
    DCIceStateFailed,
    DCIceStateClosed,
};
