// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCIceServer.h"


@implementation DCIceServer

- (nonnull instancetype)initWithHostname:(nonnull NSString *)hostname
                                    port:(int16_t)port
                                    type:(DCIceServerType)type
                                username:(nonnull NSString *)username
                                password:(nonnull NSString *)password
                               relayType:(DCIceServerRelayType)relayType
{
    if (self = [super init]) {
        _hostname = [hostname copy];
        _port = port;
        _type = type;
        _username = [username copy];
        _password = [password copy];
        _relayType = relayType;
    }
    return self;
}

+ (nonnull instancetype)IceServerWithHostname:(nonnull NSString *)hostname
                                         port:(int16_t)port
                                         type:(DCIceServerType)type
                                     username:(nonnull NSString *)username
                                     password:(nonnull NSString *)password
                                    relayType:(DCIceServerRelayType)relayType
{
    return [(DCIceServer*)[self alloc] initWithHostname:hostname
                                                   port:port
                                                   type:type
                                               username:username
                                               password:password
                                              relayType:relayType];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p hostname:%@ port:%@ type:%@ username:%@ password:%@ relayType:%@>", self.class, (void *)self, self.hostname, @(self.port), @(self.type), self.username, self.password, @(self.relayType)];
}

@end
