// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCIceState.h"
#import <Foundation/Foundation.h>


@protocol DCIceStateCallback <NSObject>

- (void)onStateChanged:(DCIceState)state;

@end
