// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCIceState.h"
#import <Foundation/Foundation.h>


@protocol DCIceStateCallback

- (void)onStateChanged:(DCIceState)state;

@end
