// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCIceServer.h"
#include "IceServer.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DCIceServer;

namespace djinni_generated {

struct IceServer
{
    using CppType = ::libdc::IceServer;
    using ObjcType = DCIceServer*;

    using Boxed = IceServer;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
