// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCIceServer.h"


@implementation DCIceServer

- (nonnull instancetype)initWithUrl:(nullable NSString *)url
                           hostname:(nonnull NSString *)hostname
                               port:(int16_t)port
                               type:(DCIceServerType)type
                           username:(nonnull NSString *)username
                           password:(nonnull NSString *)password
                          relayType:(DCIceServerRelayType)relayType
{
    if (self = [super init]) {
        _url = [url copy];
        _hostname = [hostname copy];
        _port = port;
        _type = type;
        _username = [username copy];
        _password = [password copy];
        _relayType = relayType;
    }
    return self;
}

+ (nonnull instancetype)IceServerWithUrl:(nullable NSString *)url
                                hostname:(nonnull NSString *)hostname
                                    port:(int16_t)port
                                    type:(DCIceServerType)type
                                username:(nonnull NSString *)username
                                password:(nonnull NSString *)password
                               relayType:(DCIceServerRelayType)relayType
{
    return [[self alloc] initWithUrl:url
                            hostname:hostname
                                port:port
                                type:type
                            username:username
                            password:password
                           relayType:relayType];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p url:%@ hostname:%@ port:%@ type:%@ username:%@ password:%@ relayType:%@>", self.class, (void *)self, self.url, self.hostname, @(self.port), @(self.type), self.username, self.password, @(self.relayType)];
}

#endif
@end
