// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCLibVersion+Private.h"
#import "DCLibVersion.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DCLibVersion ()

- (id)initWithCpp:(const std::shared_ptr<::libdc::LibVersion>&)cppRef;

@end

@implementation DCLibVersion {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::libdc::LibVersion>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::libdc::LibVersion>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSString *)version {
    try {
        auto objcpp_result_ = ::libdc::LibVersion::version();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto LibVersion::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto LibVersion::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DCLibVersion>(cpp);
}

} // namespace djinni_generated

@end
