// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#include "LibDC.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DCLibDC;

namespace djinni_generated {

class LibDC
{
public:
    using CppType = std::shared_ptr<::libdc::LibDC>;
    using CppOptType = std::shared_ptr<::libdc::LibDC>;
    using ObjcType = DCLibDC*;

    using Boxed = LibDC;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

