// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCLibDC+Private.h"
#import "DCLibDC.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DCLibDC ()

- (id)initWithCpp:(const std::shared_ptr<::libdc::LibDC>&)cppRef;

@end

@implementation DCLibDC {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::libdc::LibDC>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::libdc::LibDC>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSString *)version {
    try {
        auto objcpp_result_ = ::libdc::LibDC::version();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto LibDC::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto LibDC::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DCLibDC>(cpp);
}

} // namespace djinni_generated

@end
