// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

/** log */
typedef NS_ENUM(NSInteger, DCLogLevel)
{
    DCLogLevelNone,
    DCLogLevelFatal,
    DCLogLevelError,
    DCLogLevelWarning,
    DCLogLevelInfo,
    DCLogLevelDebug,
    DCLogLevelVerbose,
};
