// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#include "LogCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DCLogCallback;

namespace djinni_generated {

class LogCallback
{
public:
    using CppType = std::shared_ptr<::libdc::LogCallback>;
    using CppOptType = std::shared_ptr<::libdc::LogCallback>;
    using ObjcType = id<DCLogCallback>;

    using Boxed = LogCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

