// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "PeerConnection.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DCPeerConnection;

namespace djinni_generated {

class PeerConnection
{
public:
    using CppType = std::shared_ptr<::libdc::PeerConnection>;
    using CppOptType = std::shared_ptr<::libdc::PeerConnection>;
    using ObjcType = DCPeerConnection*;

    using Boxed = PeerConnection;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

