// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCConfiguration.h"
#import "DCDataChannelInit.h"
#import <Foundation/Foundation.h>
@class DCDataChannel;
@class DCPeerConnection;
@protocol DCCandidateCallback;
@protocol DCDcCallback;
@protocol DCGatheringStateCallback;
@protocol DCIceStateCallback;
@protocol DCSdpCallback;


@interface DCPeerConnection : NSObject

- (void)close;

- (void)setRemoteDescription:(nonnull NSString *)sdp;

- (void)addRemoteCandidate:(nonnull NSString *)candidate
                       mid:(nonnull NSString *)mid;

- (void)onLocalDescription:(nullable id<DCSdpCallback>)callback;

- (void)onLocalCandidate:(nullable id<DCCandidateCallback>)callback;

- (void)onStateChange:(nullable id<DCIceStateCallback>)callback;

- (void)onGatheringStateChange:(nullable id<DCGatheringStateCallback>)callback;

- (void)onDataChannel:(nullable id<DCDcCallback>)callback;

- (nullable DCDataChannel *)createDataChannel:(nonnull NSString *)label
                                         init:(nonnull DCDataChannelInit *)init;

+ (nullable DCPeerConnection *)create:(nonnull DCConfiguration *)config;

@end
