// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCProxyServerType.h"
#import <Foundation/Foundation.h>

@interface DCProxyServer : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithType:(DCProxyServerType)type
                            hostname:(nonnull NSString *)hostname
                                port:(int16_t)port
                            username:(nullable NSString *)username
                            password:(nullable NSString *)password NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)ProxyServerWithType:(DCProxyServerType)type
                                   hostname:(nonnull NSString *)hostname
                                       port:(int16_t)port
                                   username:(nullable NSString *)username
                                   password:(nullable NSString *)password;

@property (nonatomic, readonly) DCProxyServerType type;

@property (nonatomic, readonly, nonnull) NSString * hostname;

@property (nonatomic, readonly) int16_t port;

@property (nonatomic, readonly, nullable) NSString * username;

@property (nonatomic, readonly, nullable) NSString * password;

@end
