// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCProxyServer.h"
#include "ProxyServer.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DCProxyServer;

namespace djinni_generated {

struct ProxyServer
{
    using CppType = ::libdc::ProxyServer;
    using ObjcType = DCProxyServer*;

    using Boxed = ProxyServer;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
