// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCReliability.h"


@implementation DCReliability

- (nonnull instancetype)initWithType:(DCReliabilityType)type
                           unordered:(BOOL)unordered
                            rexmitMs:(int64_t)rexmitMs
{
    if (self = [super init]) {
        _type = type;
        _unordered = unordered;
        _rexmitMs = rexmitMs;
    }
    return self;
}

+ (nonnull instancetype)ReliabilityWithType:(DCReliabilityType)type
                                  unordered:(BOOL)unordered
                                   rexmitMs:(int64_t)rexmitMs
{
    return [[self alloc] initWithType:type
                            unordered:unordered
                             rexmitMs:rexmitMs];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p type:%@ unordered:%@ rexmitMs:%@>", self.class, (void *)self, @(self.type), @(self.unordered), @(self.rexmitMs)];
}

#endif
@end
