// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCReliability.h"
#include "Reliability.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DCReliability;

namespace djinni_generated {

struct Reliability
{
    using CppType = ::libdc::Reliability;
    using ObjcType = DCReliability*;

    using Boxed = Reliability;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
