// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCReliability+Private.h"
#import "DCReliabilityType+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Reliability::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Enum<::libdc::ReliabilityType, DCReliabilityType>::toCpp(obj.type),
            ::djinni::Bool::toCpp(obj.unordered),
            ::djinni::I64::toCpp(obj.rexmitMs)};
}

auto Reliability::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DCReliability alloc] initWithType:(::djinni::Enum<::libdc::ReliabilityType, DCReliabilityType>::fromCpp(cpp.type))
                                     unordered:(::djinni::Bool::fromCpp(cpp.unordered))
                                      rexmitMs:(::djinni::I64::fromCpp(cpp.rexmit_ms))];
}

}  // namespace djinni_generated
