// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

/**
 *config end
 * DC start
 */
typedef NS_ENUM(NSInteger, DCReliabilityType)
{
    DCReliabilityTypeReliable = 0,
    DCReliabilityTypeRexmit = 1,
    DCReliabilityTypeTimed = 2,
};
