// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

/**
 *config end
 * DC start
 */
typedef NS_ENUM(NSInteger, DCReliabilityType)
{
    DCReliabilityTypeReliable,
    DCReliabilityTypeRexmit,
    DCReliabilityTypeTimed,
};
