// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>


/**
 * DC end
 * PC start
 */
@protocol DCSdpCallback

- (void)onSdp:(nonnull NSString *)sdp;

@end
