// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#include "SdpCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DCSdpCallback;

namespace djinni_generated {

class SdpCallback
{
public:
    using CppType = std::shared_ptr<::libdc::SdpCallback>;
    using CppOptType = std::shared_ptr<::libdc::SdpCallback>;
    using ObjcType = id<DCSdpCallback>;

    using Boxed = SdpCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

