// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#import "DCSignalingState.h"
#import <Foundation/Foundation.h>


@protocol DCSignalingStateCallback

- (void)onStateChanged:(DCSignalingState)state;

@end
