// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#include "SignalingStateCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DCSignalingStateCallback;

namespace djinni_generated {

class SignalingStateCallback
{
public:
    using CppType = std::shared_ptr<::libdc::SignalingStateCallback>;
    using CppOptType = std::shared_ptr<::libdc::SignalingStateCallback>;
    using ObjcType = id<DCSignalingStateCallback>;

    using Boxed = SignalingStateCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

