// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DCTransportPolicy)
{
    DCTransportPolicyAll = 0,
    DCTransportPolicyRelay = 1,
};
