// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni

// LibDC_Bridging_Header.h
// LibDC_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for LibDCBridgingHeader.
FOUNDATION_EXPORT double LibDCBridgingHeaderVersionNumber;

//! Project version string for LibDCBridgingHeader.
FOUNDATION_EXPORT const unsigned char LibDCBridgingHeaderVersionString[];

#import "DCLogLevel.h"
#import "DCLogCallback.h"
#import "DCIceServerType.h"
#import "DCIceServerRelayType.h"
#import "DCIceServer.h"
#import "DCProxyServerType.h"
#import "DCProxyServer.h"
#import "DCCertificateType.h"
#import "DCTransportPolicy.h"
#import "DCConfiguration.h"
#import "DCReliabilityType.h"
#import "DCReliability.h"
#import "DCDataChannelInit.h"
#import "DCDcMessageCallback.h"
#import "DCDcEvent.h"
#import "DCDcEventCallback.h"
#import "DCDcErrorCallback.h"
#import "DCDataChannel.h"
#import "DCSdpCallback.h"
#import "DCCandidateCallback.h"
#import "DCIceState.h"
#import "DCIceStateCallback.h"
#import "DCGatheringState.h"
#import "DCGatheringStateCallback.h"
#import "DCSignalingState.h"
#import "DCSignalingStateCallback.h"
#import "DCDcCallback.h"
#import "DCPeerConnection.h"
#import "DCLibVersion.h"
