// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DCCertificateType)
{
    DCCertificateTypeDefault = 0,
    DCCertificateTypeEcdsa = 1,
    DCCertificateTypeRsa = 2,
};
