// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DCIceServerRelayType)
{
    DCIceServerRelayTypeTurnUdp = 0,
    DCIceServerRelayTypeTurnTcp = 1,
    DCIceServerRelayTypeTurnTls = 2,
};
