// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCLogLevel.h"
#import <Foundation/Foundation.h>


@protocol DCLogCallback <NSObject>

- (void)onLog:(DCLogLevel)level
      message:(nonnull NSString *)message;

@end
