// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import <Foundation/Foundation.h>


/**
 * DC end
 * PC start
 */
@protocol DCSdpCallback <NSObject>

- (void)onSdp:(nonnull NSString *)sdp;

@end
