// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class CertificateType : int {
    DEFAULT = 0,
    ECDSA = 1,
    RSA = 2,
};

constexpr const char* to_string(CertificateType e) noexcept {
    constexpr const char* names[] = {
        "Default",
        "Ecdsa",
        "Rsa",
    };
    return names[static_cast<int>(e)];
}

} // namespace libdc

namespace std {

template <>
struct hash<::libdc::CertificateType> {
    size_t operator()(::libdc::CertificateType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
