// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class CertificateType : int {
    DEFAULT,
    ECDSA,
    RSA,
};

}  // namespace libdc

namespace std {

template <>
struct hash<::libdc::CertificateType> {
    size_t operator()(::libdc::CertificateType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
