// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include "Reliability.hpp"
#include <cstdint>
#include <optional>
#include <string>
#include <utility>

namespace libdc {

struct DataChannelInit final {
    Reliability reliability;
    bool negotiated;
    std::optional<int16_t> id;
    std::string protocol;

    DataChannelInit(Reliability reliability_,
                    bool negotiated_,
                    std::optional<int16_t> id_,
                    std::string protocol_)
    : reliability(std::move(reliability_))
    , negotiated(std::move(negotiated_))
    , id(std::move(id_))
    , protocol(std::move(protocol_))
    {}
};

} // namespace libdc
