// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <memory>

namespace libdc {

class DataChannel;

class DcCallback {
public:
    virtual ~DcCallback() {}

    virtual void onDataChannel(const std::shared_ptr<DataChannel> & dc) = 0;
};

}  // namespace libdc
