// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include <memory>

namespace libdc {

class DataChannel;

class DcCallback {
public:
    virtual ~DcCallback() = default;

    virtual void onDataChannel(const /*not-null*/ std::shared_ptr<DataChannel> & dc) = 0;
};

} // namespace libdc
