// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <string>

namespace libdc {

class DcErrorCallback {
public:
    virtual ~DcErrorCallback() {}

    virtual void onError(const std::string & error) = 0;
};

}  // namespace libdc
