// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

namespace libdc {

enum class DcEvent;

class DcEventCallback {
public:
    virtual ~DcEventCallback() = default;

    virtual void onEvent(DcEvent event) = 0;
};

} // namespace libdc
