// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

namespace libdc {

class DcEventCallback {
public:
    virtual ~DcEventCallback() {}

    virtual void onEvent() = 0;
};

}  // namespace libdc
