// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

namespace libdc {

class DcEventCallback {
public:
    virtual ~DcEventCallback() = default;

    virtual void onEvent() = 0;
};

} // namespace libdc
