// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

namespace libdc {

enum class GatheringState;

class GatheringStateCallback {
public:
    virtual ~GatheringStateCallback() = default;

    virtual void onStateChanged(GatheringState state) = 0;
};

} // namespace libdc
