// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

namespace libdc {

enum class GatheringState;

class GatheringStateCallback {
public:
    virtual ~GatheringStateCallback() {}

    virtual void onStateChanged(GatheringState state) = 0;
};

}  // namespace libdc
