// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class GatheringState : int {
    NEW,
    INPROGRESS,
    COMPLETE,
};

}  // namespace libdc

namespace std {

template <>
struct hash<::libdc::GatheringState> {
    size_t operator()(::libdc::GatheringState type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
