// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class GatheringState : int {
    NEW = 0,
    INPROGRESS = 1,
    COMPLETE = 2,
};

constexpr const char* to_string(GatheringState e) noexcept {
    constexpr const char* names[] = {
        "New",
        "InProgress",
        "Complete",
    };
    return names[static_cast<int>(e)];
}

} // namespace libdc

namespace std {

template <>
struct hash<::libdc::GatheringState> {
    size_t operator()(::libdc::GatheringState type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
