// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class IceServerRelayType : int {
    TURNUDP,
    TURNTCP,
    TURNTLS,
};

}  // namespace libdc

namespace std {

template <>
struct hash<::libdc::IceServerRelayType> {
    size_t operator()(::libdc::IceServerRelayType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
