// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

namespace libdc {

enum class IceState;

class IceStateCallback {
public:
    virtual ~IceStateCallback() {}

    virtual void onStateChanged(IceState state) = 0;
};

}  // namespace libdc
