// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class IceServerType : int {
    STUN,
    TURN,
};

}  // namespace libdc

namespace std {

template <>
struct hash<::libdc::IceServerType> {
    size_t operator()(::libdc::IceServerType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
