// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class IceServerRelayType : int {
    TURNUDP = 0,
    TURNTCP = 1,
    TURNTLS = 2,
};

constexpr const char* to_string(IceServerRelayType e) noexcept {
    constexpr const char* names[] = {
        "TurnUdp",
        "TurnTcp",
        "TurnTls",
    };
    return names[static_cast<int>(e)];
}

} // namespace libdc

namespace std {

template <>
struct hash<::libdc::IceServerRelayType> {
    size_t operator()(::libdc::IceServerRelayType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
