// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class IceState : int {
    NEW = 0,
    CONNECTING = 1,
    CONNECTED = 2,
    DISCONNECTED = 3,
    FAILED = 4,
    CLOSED = 5,
};

constexpr const char* to_string(IceState e) noexcept {
    constexpr const char* names[] = {
        "New",
        "Connecting",
        "Connected",
        "Disconnected",
        "Failed",
        "Closed",
    };
    return names[static_cast<int>(e)];
}

} // namespace libdc

namespace std {

template <>
struct hash<::libdc::IceState> {
    size_t operator()(::libdc::IceState type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
