// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include <string>

namespace libdc {

class LibVersion {
public:
    virtual ~LibVersion() = default;

    static std::string version();
};

} // namespace libdc
