// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include <string>

namespace libdc {

enum class LogLevel;

class LogCallback {
public:
    virtual ~LogCallback() = default;

    virtual void onLog(LogLevel level, const std::string & message) = 0;
};

} // namespace libdc
