// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class LogLevel : int {
    NONE,
    FATAL,
    ERROR,
    WARNING,
    INFO,
    DEBUG,
    VERBOSE,
};

}  // namespace libdc

namespace std {

template <>
struct hash<::libdc::LogLevel> {
    size_t operator()(::libdc::LogLevel type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
