// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class ProxyServerType : int {
    HTTP = 0,
    SOCKS5 = 1,
};

constexpr const char* to_string(ProxyServerType e) noexcept {
    constexpr const char* names[] = {
        "Http",
        "Socks5",
    };
    return names[static_cast<int>(e)];
}

} // namespace libdc

namespace std {

template <>
struct hash<::libdc::ProxyServerType> {
    size_t operator()(::libdc::ProxyServerType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
