// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

#include "ProxyServerType.hpp"
#include <cstdint>
#include <optional>
#include <string>
#include <utility>

namespace libdc {

struct ProxyServer final {
    ProxyServerType type;
    std::string hostname;
    int16_t port;
    std::optional<std::string> username;
    std::optional<std::string> password;

    ProxyServer(ProxyServerType type_,
                std::string hostname_,
                int16_t port_,
                std::optional<std::string> username_,
                std::optional<std::string> password_)
    : type(std::move(type_))
    , hostname(std::move(hostname_))
    , port(std::move(port_))
    , username(std::move(username_))
    , password(std::move(password_))
    {}
};

} // namespace libdc
