// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class ReliabilityType : int {
    RELIABLE,
    REXMIT,
    TIMED,
};

}  // namespace libdc

namespace std {

template <>
struct hash<::libdc::ReliabilityType> {
    size_t operator()(::libdc::ReliabilityType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
