// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <string>

namespace libdc {

/**
 * DC end
 * PC start
 */
class SdpCallback {
public:
    virtual ~SdpCallback() {}

    virtual void onSdp(const std::string & sdp) = 0;
};

}  // namespace libdc
