// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class SignalingState : int {
    STABLE,
    HAVELOCALOFFER,
    HAVEREMOTEOFFER,
    HAVELOCALPRANSWER,
    HAVEREMOTEPRANSWER,
};

}  // namespace libdc

namespace std {

template <>
struct hash<::libdc::SignalingState> {
    size_t operator()(::libdc::SignalingState type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
