// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#pragma once

namespace libdc {

enum class SignalingState;

class SignalingStateCallback {
public:
    virtual ~SignalingStateCallback() = default;

    virtual void onStateChanged(SignalingState state) = 0;
};

} // namespace libdc
