// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libdc.djinni

#pragma once

#include <functional>

namespace libdc {

enum class TransportPolicy : int {
    ALL,
    RELAY,
};

}  // namespace libdc

namespace std {

template <>
struct hash<::libdc::TransportPolicy> {
    size_t operator()(::libdc::TransportPolicy type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
