// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from libdc.djinni

#import "DCDcEvent.h"
#import <Foundation/Foundation.h>


@protocol DCDcEventCallback <NSObject>

- (void)onEvent:(DCDcEvent)event;

@end
